// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMeal(arg1) {
  return window['go']['repository']['MealRepository']['CreateMeal'](arg1);
}

export function DeleteMeal(arg1) {
  return window['go']['repository']['MealRepository']['DeleteMeal'](arg1);
}

export function GetMeal(arg1) {
  return window['go']['repository']['MealRepository']['GetMeal'](arg1);
}

export function GetMeals() {
  return window['go']['repository']['MealRepository']['GetMeals']();
}

export function GetMealsByName(arg1) {
  return window['go']['repository']['MealRepository']['GetMealsByName'](arg1);
}

export function UpdateMeal(arg1) {
  return window['go']['repository']['MealRepository']['UpdateMeal'](arg1);
}
