// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateMeal(arg1:models.MealDTO):Promise<models.MealDTO>;

export function DeleteMeal(arg1:string):Promise<void>;

export function GetMeal(arg1:string):Promise<models.MealDTO>;

export function GetMeals():Promise<Array<models.MealDTO>>;

export function GetMealsByName(arg1:string):Promise<Array<models.MealDTO>>;

export function UpdateMeal(arg1:models.MealDTO):Promise<models.MealDTO>;
