// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRecord(arg1) {
  return window['go']['repository']['TrackingRepository']['CreateRecord'](arg1);
}

export function DeleteDailyDiet(arg1) {
  return window['go']['repository']['TrackingRepository']['DeleteDailyDiet'](arg1);
}

export function DeleteRecord(arg1) {
  return window['go']['repository']['TrackingRepository']['DeleteRecord'](arg1);
}

export function GetDailyDiet(arg1) {
  return window['go']['repository']['TrackingRepository']['GetDailyDiet'](arg1);
}

export function GetDailyNutritionalInfo(arg1) {
  return window['go']['repository']['TrackingRepository']['GetDailyNutritionalInfo'](arg1);
}

export function GetRecord(arg1) {
  return window['go']['repository']['TrackingRepository']['GetRecord'](arg1);
}

export function UpdateRecord(arg1) {
  return window['go']['repository']['TrackingRepository']['UpdateRecord'](arg1);
}

export function UpsertDailyDiet(arg1) {
  return window['go']['repository']['TrackingRepository']['UpsertDailyDiet'](arg1);
}
